format_version: 3
pipelines:
  agent-static-hugo:
    group: gocd-agents
    label_template: "${gitrepo[:8]}"
    lock_behavior: none
    environment_variables:
      PROJECT: static-hugo
    materials:
      gitrepo:
        git: git@gitlab.com:ikethecoder/yamya-infra.git
        branch: develop
    stages:
      - deploy:
          clean_workspace: true
          elastic_profile_id: "docker"
          tasks:
          - script: |
              cd cicd-agents/static-hugo
              docker build --tag $PROJECT.local .
              docker tag $PROJECT.local $REGISTRY/agents/${PROJECT}:latest
              docker push $REGISTRY/agents/${PROJECT}

